// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ4aCBpO4ejYThtjxD_ojqtbUAz5dcaQA',
    appId: '1:442487503135:web:a2f8c50cdce4a0832c582a',
    messagingSenderId: '442487503135',
    projectId: 'chat-cbada',
    authDomain: 'chat-cbada.firebaseapp.com',
    storageBucket: 'chat-cbada.appspot.com',
    measurementId: 'G-BRQ56Q0NXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYuiacpOIhvjDza2sgHNoGIV2k5Z3g9HE',
    appId: '1:442487503135:android:112d1ecad0b428a12c582a',
    messagingSenderId: '442487503135',
    projectId: 'chat-cbada',
    storageBucket: 'chat-cbada.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDErfM1pZQT8pNBHt8v1RoDf7JwzTr4u4',
    appId: '1:442487503135:ios:b333c7013bff7f722c582a',
    messagingSenderId: '442487503135',
    projectId: 'chat-cbada',
    storageBucket: 'chat-cbada.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDErfM1pZQT8pNBHt8v1RoDf7JwzTr4u4',
    appId: '1:442487503135:ios:18da66f45b5ec0482c582a',
    messagingSenderId: '442487503135',
    projectId: 'chat-cbada',
    storageBucket: 'chat-cbada.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
